== Server SoC Hardware Requirements

=== RISC-V Harts

A RISC-V SoC includes an RISC-V application processor and may include one or
more service processors. The service processors may provide services such as
security and power management to software executing on the application
processors and may themself implement the RISC-V ISA. The requirements in 
this section only apply to harts in the application processors of the SoC.

[width=100%]
[%header, cols="5,20"]
|===
| ID#     ^| Requirement
| RVA_010  | The RISC-V application processor harts in the SoC MUST support the
             RVA23 ISA profile cite:[RVA23].
2+| _The next major release of the profiles is expected to be RVA24 which is
     still under construction. This specification should be updated to comply
     with the RVA24 profiles as the profile definition firms up._

| RVA_020  | The RISC-V application processor harts in the SoC MUST support the
             following extensions:
             * Sv48
             * Sv48x4
             * Svadu
             * Sdtrig
             * Sdext
             * H
             * Sscofpmf
             * Zkr
             * Ssecorrupt
             * Ssccfg
             * Ssctr
             * Sscrind
2+| _Ssccfg, Sscind, and Ssctr are under construction._                       +
                                                                              +
    _Many of these mandated extensions are optional in the RVA23 ISA profile.
     This requirement is placed here as a placeholder. These mandates may be
     moved downstream into a platform spec (as a chapter) or as a new ISA
     profile spec._

| RVA_030  | The ISA extensions and associated CSR field widths implemented by
             any of the  RISC-V application processor harts in the SoC MUST be
             identical.
2+| _The RVA23 profile supports a set of optional extensions. The set of
     optional extensions implemented by the harts must be identical. Where the
     extension supports optionality in the form of width of fields (e.g.,
     ASIDLEN, VLEN, allowed vstart values, physical address width, debug
     triggers, cache-block size, etc.), the implementation of these must also be
     identical. Identical ISA on all harts allows system software to migrate
     tasks among the harts without constraints._

| RVA_040  | The RISC-V application processor harts in the SoC MAY support
             different power and performance characteristics but must be
             otherwise indistinguishable from each other from a software
             execution viewpoint.
2+| _All harts in the SoC being indistinguishable from a software execution
     viewpoint allows system software to migrate tasks among the harts without
     constraints._

| RVA_050  | The RISC-V application processor hart MUST support:
             . Single stepping using the step bit in  dcsr 
             . Debug scratch register 0 (dscratch0)

| RVA_060  | The RISC-V application processor hart MUST support:
             . At least 6 instruction address match triggers
             . At least 6 load/store address match triggers
             . At least one icount trigger to support single stepping 
             . At least one interrupt trigger
             . At least one exception trigger
             . Trigger filtering using `hcontext`
             . Trigger filtering using all VMID encodings supported by the hart
             . Trigger filtering using `scontext`
             . Trigger filtering using all ASID encodings supported by the hart

| RVA_070  | The RISC-V application process MUST support at least 6 hardware
             performance counters defined by the Zihpm extension in addition to
             the three counters defined by Zicntr extension.
|===

=== Clocks and Timers

[width=100%]
[%header, cols="5,20"]
|===
| ID#     ^| Requirement
| CTI_010  | The `time` CSR MUST increment at a constant frequency and the count
             MUST be in units of 1 ns. The frequency at which the CSR provides
             an updated time value must be at least 100 MHz.
| CTI_002  | The `time` counter MUST appear to be always on and MUST appear to
             not lose its count across power states including when the hart is
             powered off.
|===

=== External Interrupt Controllers

This section specifies the requirements on the interrupt controllers used to
deliver external interrupts to the RISC-V application processor harts.

[width=100%]
[%header, cols="5,20"]
|===
| ID#     ^| Requirement
| IIC_010  | The RISC-V Advanced Interrupt Architecture cite:[AIA] MUST be
             supported.

| IIC_020  | External interrupts MUST be signaled to a hart as message-signaled
             interrupts (MSI).
2+| _MSI being memory writes allow simplified implementation of rules such as
     interrupts following a write from a device must only be observed after the
     writes have been observed and the read completion generated by a device
     following an interrupt must only be observed after the interrupt has been
     observed._                                                                +
                                                                               +
    _Message Signaled interrupts (MSI) is the preferred interrupt signaling
     mechanism in PCIe. Supporting MSI to harts allows allows low latency
     interrupt signaling._

| IIC_030  | The IMSIC MUST implement an interrupt file for S-mode.

| IIC_040  | The IMSIC MUST support at least 5 VS-mode interrupt files.
2+| _Supporting 5 VS-mode interrupt files for a hart allows context switching
     between up to 5 virtual CPUs (vCPU) on a hart without needing to swap the
     contents of the interrupt file out to memory. Especially when devices are
     directly assigned to VMs, swapping out the context of an IMSIC interrupt
     file may incur longer latencies due to the need to redirect device
     interrupts to a memory resident interrupt file._

| IIC_050  | The S-mode interrupt files MUST support at least 255 interrupt
             identities.

| IIC_060  | The VS-mode interrupt files MUST support at least 63 interrupt
             identities.

| IIC_070  | The memory regions for IMSIC interrupt files MUST have the
             following PMAs:
             . Not cacheable, coherent, I/O region
             . Supports 4 byte aligned reads and writes

| IIC_080  | If the SoC implements devices that use wire-signaled interrupts
             then the SoC MUST implement an APLIC as specified by the RISC-V
             AIA specification and MUST use the APLIC to convert the
             wire-signaled interrupts into MSIs.                               +
                                                                               +
             If implemented, the APLIC MUST support:
             * Supervisor interrupt domain
             * GEILEN equal to that implemented by the harts
             * MSI delivery mode
             * Extempore MSI generation using genmsi register
2+| _SoC devices using wire-signaled interrupts must implement the rules related
     to ordering of interrupts vs. older read/writes from devices as specified
     by the device and/or bus interface specifications that such devices conform
     to. See also SID_006.
|===

=== Input-Output Memory Management Unit (IOMMU)

[width=100%]
[%header, cols="5,20"]
|===
| ID#     ^| Requirement
| IOM_010  | All IOMMUs in the SoC MUST support the RISC-V IOMMU specification
             cite:[IOMMU].
2+| _The number of IOMMUs implemented in the SoC is UNSPECIFIED._

| IOM_020  | All DMA capable peripherals (RCiEP and non-PCIe devices) and all
             PCIe root ports that are made available to software on the RISC-V
             application processor harts MUST be governed by an IOMMU.         +
                                                                               +
             This requirement does not apply to platform devices such as the
             APLIC or the IOMMU itself. This requirement does not apply to
             memory accesses originated by a debug module using a System Bus
             Access block.
2+| _DMA capable peripherals being governed by an IOMMU allows OS/hypervisors to
     restrict DMA originating from such devices to a subset of memory to enhance
     security and software fault tolerance. The address translation capability
     provided by the IOMMU enables usages such as passthrough of such devices to
     virtual machines, shared virtual addressing, etc._

| IOM_030  | The IOMMU governing a PCIe root port MUST support at least 16-bit
             wide device IDs. 

| IOM_040  | An IOMMU that does not govern a PCIe root port MUST support a
             device ID width required to support all requester IDs originated by
             the devices governed by that IOMMU.

| IOM_050  | The IOMMU MUST implement all the page based virtual memory system
             modes and extensions that are supported by the IOMMU and are also 
             implemented by the RISC-V application processor harts in the SoC.
2+| _The page based virtual memory system modes that may be optionally supported
     by the IOMMU are defined in the IOMMU capabilities register._

| IOM_060  | The IOMMU SHOULD support the following virtual memory extensions:
             * Svadu (enumerated by 1 setting of `capabilities.AMO_HWAD`)
2+| _Hardware A/D bit updates capability enables efficient support for use
     models such as VM migration, shared virtual addressing, and user space work
     submission._

| IOM_070  | The IOMMU SHOULD support pass-through mode and MRIF mode MSI
             address translation.

| IOM_080  | When MRIF mode MSI address translation is supported, the IOMMU MUST
             support atomic updates to the MRIF (enumerated by 1 setting of
             `capabilities.AMO_MRIF`).

| IOM_090  | IOMMU governing PCIe root ports SHOULD support PCIe address 
             translation services (ATS). 
2+| _High performance devices such as DPU/SmartNICs, GPUs, and FPGAs used in
     server platforms rely on ATS and Page Request services to deliver high
     throughput and low latency I/O.                                           +
     Supporting ATS is also required for efficiently supporting usage models
     such as Shared Virtual Addressing and direct work submission from user
     mode._

| IOM_100  | IOMMU governing PCIe root ports SHOULD support the T2GPA mode of
             operation with ATS if ATS is supported.

| IOM_110  | IOMMU governing RCiEP MUST support PCIe address translation
             services (ATS) if any of the RCiEP governed by the IOMMU support
             the ATS capability.
2+| _The T2GPA control enables a hypervisor to contain DMA from a device, even
     if the device misuses the ATS capability and attempts to access memory that
     is not explicitly authorized by the page tables governing that devices
     memory accesses. The threat model may also include a man-in-the-middle on
     the PCIe link inserting ATS translated requests to access memory that was
     not previously authorized.  As an alternative to setting T2GPA to 1, the
     hypervisor may establish a trust relationship with the device if
     authentication protocols are supported by the device. For PCIe, for
     example, the PCIe component measurement and authentication (CMA) capability
     provides a mechanism to verify the device’s configuration and 
     firmware/executable (Measurement) and hardware identities (Authentication)
     to establish such a trust relationship and the PCIe link may be integrity
     protected using PCIe integrity and data encryption (IDE)._

| IOM_120  | IOMMU governing RCiEP MAY support the T2GPA mode of operation with
             ATS if ATS is supported.
2+| _The threats associated with misuse of ATS or malicious insertion of ATS
     translated requests by a man-in-the-middle may not be present with RCiEP
     being integrated in the SoC._

| IOM_130  | IOMMU MUST support MSI and MAY support wire-signaled interrupts
             for external interrupts originated by the IOMMU itself.

| IOM_140  | IOMMU MUST support little-endian memory access to its in-memory
             data structures.

| IOM_150  | IOMMU MAY support big-endian mode memory access to its in-memory
             data structures.
2+| _The IOMMU memory-mapped registers always have a little-endian byte order._

| IOM_160  | IOMMU MAY support the PASID capability.

| IOM_170  | IOMMU that supports PASID capability MUST support 20-bit PASID
             width and MAY support 8 and 17 bit PASID width.
2+| _PCIe specification strongly recommends that hardware implement the maximum
     width of 20 bits to ensure interoperability with system software. See also
     the implementation note on PASID width homogeneity in the PCIe
     specification 6.0 section 6.20.2.2._

| IOM_180  | IOMMU SHOULD support a hardware performance monitor (HPM).
2+| _The HPM is a valuable tool for system integrators for performance
     monitoring and optimizations. An IOMMU is highly recommended to provide a
     HPM._

| IOM_190  | IOMMU that supports a HPM, MUST support the cycles counter and at
             least 4 event counters. 

| IOM_200  | The cycles counter and the event counters MUST be at least 40-bit
             wide.

| IOM_210  | The IOMMU SHOULD support the software debug capabilities enumerated
             by `capabilities.DBG`.

| IOM_220  | The physical address width supported by the IOMMU MUST be greater
             than or equal to the physical address width supported by the RISC-V
             application processor harts in the SoC.
2+| _The physical address width being greater than or equal to the width
     supported the harts in the SoC enables use of all addressable memory for
     I/O and enables sharing of page tables between the hart MMU and the IOMMU._

| IOM_230  | The reset default of the `iommu_mode` MUST be `Off`.
2+| _The IOMMU disallowing DMA unconditionally following reset due to the mode
     being Off allows the SoC firmware and software to enable DMA when
     suitable security protections as required have been established. The IOMMU
     mode being Off at reset does not pose a significant issue to SoC firmware
     that needs to employ DMA (e.g., for firmware loading) as that firmware may
     program the mode in the appropriate IOMMU prior to programming the
     peripheral governed by that IOMMU to perform a DMA._

| IOM_240  | The IOMMU SHOULD be implemented as a RCiEP with base class 08H and
             subclass 06H cite:[PCI_CLS].
2+| _The base class 08H and sub-class 06H are designated by PCIe for use by an
     IOMMU. Implementing the IOMMU as a PCIe device allows an operating system
     to determine a driver for the IOMMU and to assign resources such as
     interrupt vectors to the IOMMU in a PCIe compatible manner._

| IOM_250  | The host bridge MUST enforce the physical memory attribute checks
             and physical memory protection checks on memory accesses originated
             by the IOMMU and signal detected access violations to the IOMMU.

2+| _These checks are analogous to the PMA and PMP checks performed by the
     RISC-V hart. The host bridge (also known as IO bridge) invokes the IOMMU
     for address translations. To perform the operations requested by the host
     bridge the IOMMU may need to access in-memory data structures such as the
     device directory table and page tables._

| IOM_260  | An IOMMU MUST support 24-bit device IDs if the IOMMU governs
             multiple PCIe root ports that may be part of different PCIe
             hierarchies.
2+| _An IOMMU governing PCIe root ports uses requester ID (RID) - the tuple of
     bus/device/function numbers (or just bus/function numbers, if the PCIe ARI
     option is used) - to locate a device context to use for address
     translation and protection. The 16-bit RID uniquely identifies a requester
     within a hierarchy. This RID needs to be augmented with the Hierarchy ID
     (also known as segment ID) - a 8-bit number - to uniquely identify a
     requester across PCIe hierarchies._

| IOM_270  | The host bridge MUST provide the PCIe RID as the bits 15:0 of the
             device_id to the IOMMU for requests from PCIe EPs and RCiEP.

| IOM_280  | When the IOMMU supports 24-bit device IDs, the host bridge MUST
             specify the segment number associated with the PCIe hierarchy from
             which requests were received as the bits 23:16 of the device_id to
             the IOMMU. 

| IOM_290  | The determination of device_id input to an IOMMU for requests
             originating from non-PCIe devices is UNSPECIFIED. If PCIe and
             non-PCIe endpoints/RCiEP are governed by the same IOMMU, the SoC
             MUST ensure that there is no overlap between device_id associated
             with non-PCIe devices with the device_id formed using the PCIe
             RID (and if applicable the segment ID).
|===

=== PCIe Subsystem Integration

A PCIe subsystem consists of a root complex with a collection of root ports,
root complex event collectors (RCECs), root complex register blocks (RCRBs),
and root complex integrated end points (RCiEPs). The root complex implements
a host bridge to connect the PCIe root ports, RCECs, RCRBs, and RCiEP, to the
CPU and system memory in the SoC through an interconnect.

One or more root ports in a root complex may be part of a hierarchy where a
hierarchy is a PCI Express I/O interconnect topology, wherein the Configuration
Space addresses, referred to as the tuple of Bus/Device/Function Numbers (or
just Bus/Function Numbers, for PCIe ARI cases), are unique. These addresses are
used for Configuration Request routing, Completion routing, some Message
routing, and for other purposes. In some contexts a Hierarchy is also called a
Segment, and in Flit Mode, the Segment number is sometimes also included in the
ID of a Function. Each root port in a hierarchy originates a hierarchy domain
i.e. a part of a Hierarchy originating from a single Root Port. The root ports
are PCI-PCI bridges that bridge a primary PCIe bus to a range of secondary and
subordinate buses. 

In some SoCs, devices may be integrated in the same package/die as the root
complex. Examples of such devices are network controllers, USB host controllers,
NVMe controllers, AHCI controllers, etc. Such SoC integrated devices may be
presented to software using one of the following options:
. Presented to software as a PCIe endpoint (EP; See section 1.3.2.2 of the PCIe
  6.0 specification) connected to a PCIe root port. Such PCIe endpoints must
  comply with the PCIe specified rules for endpoints. 
. Presented to software as a root complex integrated endpoint (RCiEP; See
  section 1.3.2.3 of the PCIe 6.0 specification). Such PCIe endpoints must
  comply with the PCIe specified rules for RCiEP. 

The host Bridge is placed between the device(s) and the system interconnect to
process DMA transactions. Devices perform DMA transactions using IO Virtual
Addresses (VA, GVA or GPA). The host bridge invokes the associated IOMMU to
translate the IOVA to Supervisor Physical Addresses (SPA).

==== Enhanced Configuration Access Method (ECAM)

==== PCIe Memory Space

==== Access Control Services (ACS)

==== Address Routed Transactions

==== ID Routed Transactions

==== Cacheability and Coherence

==== Message signaled interrupts

==== Precision Time Management

==== Error and Event Reporting

==== Vendor Specific Registers

==== SoC Integrated PCIe Devices

=== Reliability, Availability, and Serviceability (RAS)

=== Quality of Service

=== Manageability

=== Debug

=== Trace

=== Performance Monitoring

=== Security Requirements
